#! /bin/bash

clear

rm -rf dist

if [[ $1 == '--dev' ]]; then

  echo """
  ====================
  DEVELOPING JS BUNDLE
  ====================
  """

  TS_NODE_PROJECT=webpack.tsconfig.json \
    DEBUG=true \
    DEV_PORT=3000 \
    NODE_ENV=development \
    ./node_modules/.bin/webpack-dev-server --colors --config webpack.config.ts --mode development

else

  echo """
  ==================
  BUILDING JS BUNDLE
  ==================

  (Use --dev for watch mode)

  """

  TS_NODE_PROJECT=webpack.tsconfig.json \
    NODE_ENV=production \
    ./node_modules/.bin/webpack --colors --config webpack.config.ts --mode production --json >compilation-stats.json

  ln -fs $PWD/images $PWD/dist/images

fi
